# Amazon Books Dataset

In [1]:
import pandas as pd
import altair as alt

In [4]:
books = pd.read_csv("datasets/amazon_com_extras.csv")
books.head()

,ASIN,GROUP,FORMAT,TITLE,AUTHOR,PUBLISHER,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,1250150183,book,hardcover,The Swamp: Washington's Murky Pool of Corrupti...,Eric Bolling,St. Martin's Press,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,778319997,book,hardcover,"Rise and Shine, Benedict Stone: A Novel",Phaedra Patrick,Park Row Books,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1608322564,book,hardcover,Sell or Be Sold: How to Get Your Way in Busine...,Grant Cardone,Greenleaf Book Group Press,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,310325331,book,hardcover,Christian Apologetics: An Anthology of Primary...,"Khaldoun A. Sweis, Chad V. Meister",Zondervan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,312616295,book,hardcover,Gravity: How the Weakest Force in the Universe...,Brian Clegg,St. Martin's Press,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
books["Unnamed: 9"].value_counts()

 Black and Proud Blerd                                      1
 Linda Barnes 'Ph.D.  M.A.                                  1
 Preschool ... learn) (The Terry Treetop Series Book 1)'    1
 Music                                                      1
Brookes Publishing                                          1
Name: Unnamed: 9, dtype: int64